services:
  redis-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "6379:6379"
    networks:
      - redis-network
    restart: unless-stopped
    hostname: redis-server

  redis-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - redis-server
    networks:
      - redis-network
    stdin_open: true
    tty: true
    command: [ "./build/client/client", "redis-server", "6379" ]

networks:
  redis-network:
    driver: bridge
